#!/bin/zsh

# Default programs:
EDITOR=vim

# ~/ Clean-up:
export ZDOTDIR="$HOME/.config/zsh"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export HISTFILE="$XDG_DATA_HOME/history"
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
